### ISSUE TITLE
Splash screen 

### ISSUE THREAD

**Issue by aboabdelaziz** [cait-g1/sahel-support#7]
![Screenshot_20200518-103957](https://user-images.githubusercontent.com/36797115/82187097-922baf00-98f4-11ea-8b37-e1f34b27350c.jpg)

Once I open up the App, I got this screen and it's freezing there! 

 - OS: Android 9
 - Device name: Galaxy S8

**Comment by Mohd-3** [comment]
This is because you have added wrong service status:

![Screenshot from 2020-05-18 23-21-26](https://user-images.githubusercontent.com/57235933/82256203-97bddf00-995e-11ea-8f6a-efd90ae73d7e.png)

As mentioned in the docs, `data_table` (service body above) should be in `json` format and not a `list` of json objects. I have changed that service status. Also, the `identifier_value` will be shown as title of the service status in the mobile app and it should be unique for that service status so it should be passport number:

![Screenshot from 2020-05-18 23-24-26](https://user-images.githubusercontent.com/57235933/82256455-069b3800-995f-11ea-9fd6-54e624954b5d.png)

In passport service type, `identifier_key` should be رقم الجواز because that will show in the service status title:

![Screenshot from 2020-05-18 23-25-27](https://user-images.githubusercontent.com/57235933/82256510-23d00680-995f-11ea-88fe-f8791d19dffa.png)

After fix:

![Screenshot from 2020-05-18 23-25-57](https://user-images.githubusercontent.com/57235933/82256529-2cc0d800-995f-11ea-846a-c8b608e60f3f.png)

For more explanation, please check service status in your mobile app now.

**Comment by aboabdelaziz** [comment]
the mobile app is not working, i'm getting "Splash page" only!

**Comment by Mohd-3** [comment]
I just logged in with your civil ID and it is working fine, can you try restarting the mobile app? It should ask you to login now.

**Comment by aboabdelaziz** [comment]
Nothing changed here! even I did clear cache data, clear app data, force stop the app and uninstall it.. and finally installed it again!!!

**Comment by aboabdelaziz** [comment]
..Also I have downloaded the App on Galaxy tablet S5, Android 9, but still I'm facing the same issue!
